config/routes.rb
RevTilt::Application.routes.draw do
  root :to => "pages#about"
  
  devise_for :users
  
  get "/about" => "pages#about"
  get "/bookmarklet" => "pages#bookmarklet"
  get "/favorites" => "pages#favorites"
  get "/press" => "pages#press"
  
  resources :organizations
  resources :reviews
  
  namespace :relationships do
    resources :organization_users do
      collection do
        post :favorite
        delete :unfavorite
      end
    end
  end

  namespace :api do
    namespace :v1 do
      get "/documentation" => "pages#documentation"
      resources :organizations, :only => [:index, :show]
    end
  end

end

app/models/relationships/organization_user.rb
# == Schema Information
# Schema version: 20130423230554
#
# Table name: relationships_organization_users
#
#  id              :integer          not null, primary key
#  organization_id :integer
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Relationships::OrganizationUser < ActiveRecord::Base
  # attr_accessible :organization_id, :user_id
  
  validates_presence_of :organization_id
  validates_presence_of :user_id
  
  belongs_to :organization, :class_name => "Organization", :foreign_key => "organization_id"
  belongs_to :user, :class_name => "User", :foreign_key => "user_id"
end

app/controllers/relationships/organization_users_controller.rb
class Relationships::OrganizationUsersController < ApplicationController
  before_filter :authenticate_user!

  # GET /relationships/organization_users
  # GET /relationships/organization_users.json
  def index
    @relationships_organization_users = Relationships::OrganizationUser.paginate(:page => params[:page])

    authorize! :index, Relationships::OrganizationUser

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @relationships_organization_users }
    end
  end

  # GET /relationships/organization_users/1
  # GET /relationships/organization_users/1.json
  def show
    @relationships_organization_user = Relationships::OrganizationUser.find(params[:id])

    authorize! :show, @relationships_organization_user

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @relationships_organization_user }
    end
  end

  # GET /relationships/organization_users/new
  # GET /relationships/organization_users/new.json
  def new
    @relationships_organization_user = Relationships::OrganizationUser.new

    authorize! :new, @relationships_organization_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @relationships_organization_user }
    end
  end

  # GET /relationships/organization_users/1/edit
  def edit
    @relationships_organization_user = Relationships::OrganizationUser.find(params[:id])

    authorize! :edit, @relationships_organization_user
  end

  # POST /relationships/organization_users
  # POST /relationships/organization_users.json
  def create
    @relationships_organization_user = Relationships::OrganizationUser.new(permitted_params)

    authorize! :create, @relationships_organization_user

    respond_to do |format|
      if @relationships_organization_user.save
        format.html { redirect_to @relationships_organization_user, notice: 'Organization user was successfully created.' }
        format.json { render json: @relationships_organization_user, status: :created, location: @relationships_organization_user }
      else
        format.html { render action: "new" }
        format.json { render json: @relationships_organization_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /relationships/organization_users/1
  # PUT /relationships/organization_users/1.json
  def update
    @relationships_organization_user = Relationships::OrganizationUser.find(params[:id])

    authorize! :update, @relationships_organization_user

    respond_to do |format|
      if @relationships_organization_user.update_attributes(permitted_params)
        format.html { redirect_to @relationships_organization_user, notice: 'Organization user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @relationships_organization_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/organization_users/1
  # DELETE /relationships/organization_users/1.json
  def destroy
    @relationships_organization_user = Relationships::OrganizationUser.find(params[:id])

    authorize! :destroy, @relationships_organization_user

    @relationships_organization_user.destroy

    respond_to do |format|
      format.html { redirect_to relationships_organization_users_url }
      format.json { head :no_content }
    end
  end
  
  # POST /relationships/organization_users/favorite
  # POST /relationships/organization_users/favorite.js
  # POST /relationships/organization_users/favorite.json
  def favorite
    @organization = Organization.find(params[:organization_id])
    @relationships_organization_user = current_user.favorite!(@organization)
    
    respond_to do |format|
      format.html { redirect_to @organization }
      format.json { render json: @relationships_organization_user, status: :created }
      format.js
    end
  end
  
  # DELETE /relationships/organization_users/unfavorite
  # DELETE /relationships/organization_users/unfavorite.js
  # DELETE /relationships/organization_users/unfavorite.json
  def unfavorite
    @organization = Organization.find(params[:organization_id])
    @relationships_organization_user = current_user.unfavorite!(@organization)
    
    respond_to do |format|
      format.html { redirect_to @organization }
      format.json { render json: @relationships_organization_user, status: :created }
      format.js
    end
  end
  
  protected
  
  def permitted_params
    params.require(:relationships_organization_user).permit(:organization_id, :user_id)
  end
end

app/helpers/relationships/organization_users_helper.rb
module Relationships::OrganizationUsersHelper
end

app/views/relationships/organization_users/_favorite.html.erb
<%= link_to favorite_relationships_organization_users_path(:organization_id => organization.to_param), 
    :class => "btn btn-default favorite-btn", :method => :post, :remote => true do %>
  <i class="glyphicon glyphicon-star"></i>
  Favorite
<% end %>

app/views/relationships/organization_users/_favorite_form.html.erb
<% if signed_in? %>
  <%= content_tag :div, :class => "o#{organization.to_param} organization_favorite_form" do %>
    <% if current_user.favorited?(organization) %>
      <%= render 'relationships/organization_users/unfavorite', :organization => organization %>
    <% else %>
      <%= render 'relationships/organization_users/favorite', :organization => organization %>
    <% end %>
  <% end %>
<% end %>

app/views/relationships/organization_users/_form.html.erb
<%= form_for @relationships_organization_user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :organization_id, :class => 'control-label col-xs-2' %>
    <div class="col-xs-5">
      <%= f.number_field :organization_id, :class => 'form-control number_field' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-xs-2' %>
    <div class="col-xs-5">
      <%= f.number_field :user_id, :class => 'form-control number_field' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-xs-5 col-xs-offset-2">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  relationships_organization_users_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/relationships/organization_users/_unfavorite.html.erb
<%= link_to unfavorite_relationships_organization_users_path(:organization_id => organization.to_param), 
            :class => "favorite-btn unfavorite btn btn-success", :method => :delete, :remote => true do %>
  <i class="glyphicon glyphicon-ok default"></i>
  <i class="glyphicon glyphicon-remove hover hide"></i>
  <span class="message default">Favorite</span>
  <span class="message hover hide">Unfavorite</span>
<% end %>

app/views/relationships/organization_users/edit.html.erb
<%- model_class = Relationships::OrganizationUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/relationships/organization_users/favorite.js.erb
$(".o<%= @organization.to_param %>").html("<%= escape_javascript(render('relationships/organization_users/unfavorite', :organization => @organization)) %>");
unfavorite_button_hover();

app/views/relationships/organization_users/index.html.erb
<%- model_class = Relationships::OrganizationUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:organization_id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @relationships_organization_users.each do |organization_user| %>
      <tr>
        <td><%= link_to organization_user.id, relationships_organization_user_path(organization_user) %></td>
        <td><%= organization_user.organization_id %></td>
        <td><%= organization_user.user_id %></td>
        <td><%=l organization_user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_relationships_organization_user_path(organization_user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      relationships_organization_user_path(organization_user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_relationships_organization_user_path,
            :class => 'btn btn-primary' %>

app/views/relationships/organization_users/new.html.erb
<%- model_class = Relationships::OrganizationUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/relationships/organization_users/show.html.erb
<%- model_class = Relationships::OrganizationUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:organization_id) %>:</strong></dt>
  <dd><%= @relationships_organization_user.organization_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @relationships_organization_user.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              relationships_organization_users_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_relationships_organization_user_path(@relationships_organization_user), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              relationships_organization_user_path(@relationships_organization_user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/relationships/organization_users/unfavorite.js.erb
$(".o<%= @organization.to_param %>").html("<%= escape_javascript(render('relationships/organization_users/favorite', :organization => @organization)) %>");