config/routes.rb
RevTilt::Application.routes.draw do
  root :to => "pages#about"
  
  devise_for :users
  
  get "/about" => "pages#about"
  get "/bookmarklet" => "pages#bookmarklet"
  get "/favorites" => "pages#favorites"
  get "/press" => "pages#press"
  
  resources :organizations
  resources :reviews
  
  namespace :relationships do
    resources :organization_users do
      collection do
        post :favorite
        delete :unfavorite
      end
    end
  end

  namespace :api do
    namespace :v1 do
      get "/documentation" => "pages#documentation"
      resources :organizations, :only => [:index, :show]
    end
  end

end

app/models/organization.rb
# == Schema Information
# Schema version: 20130501180835
#
# Table name: organizations
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  url              :string(255)
#  url_type         :string(255)
#  latitude         :float
#  longitude        :float
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  category_id      :integer
#  address          :string(255)
#  display_location :string(255)
#  homepage_url     :string(255)
#

require "open-uri"

class Organization < ActiveRecord::Base
  # attr_accessible :address, :category_id, :homepage_url, :latitude, :longitude, :name, :url

  # Validations
  validates_presence_of :category_id
  validates_presence_of :name
  validates_presence_of :url, :message => "must be a yelp URL"
  validates_uniqueness_of :url
  validates_format_of :homepage_url, with: UrlFormatter.url_regexp, message: "is not a valid URL", if: "homepage_url?"
  validates_presence_of :address
  
  # Database Relationships
  has_many :organization_user_relationships, :class_name => "Relationships::OrganizationUser", :foreign_key => "organization_id", 
           :dependent => :destroy
  has_many :reviews, :class_name => "Review", :foreign_key => "organization_id"
  has_many :users, :through => :organization_user_relationships, :source => :user
  
  has_many :cache_review_stats, :class_name => "Cache::ReviewStat", :foreign_key => "organization_id", :dependent => :destroy
  
  # URL cleaning
  before_validation :clean_url
  
  # Based on https://github.com/nhocki/url_formatter
  before_validation do
    self.homepage_url = UrlFormatter.format_url(self.homepage_url)
  end
  
  # Geocoding
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  
  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if geo = results.first
      obj.display_location = [geo.city, geo.state_code, geo.postal_code].join(", ")
    end
  end
  after_validation :reverse_geocode, :if => :address_changed?
  
  # Class Methods
  def self.category_options
    return { "activities" => 1, 
             "childcare / home care" => 2,
             "dentist / orthodontist" => 3, 
             "education" => 7, 
             "hair salon / barber" => 5, 
             "healthcare" => 4,
             "housing" => 14,
             "non-profit / government" => 13,
             "other" => 0,
             "restaurants" => 6, 
             "therapy - cognitive behavioral" => 10,
             "therapy - occupational" => 9,
             "therapy - speech & language" => 8,
             "therapy - physical" => 12,
             "therapy - other" => 11 }
  end
  
  def self.category_text(q_category_id)
    Organization.category_options.select { |k,v| v == q_category_id }.keys[0] rescue "MISC"
  end
  
  def self.with_url(q_url)
    where(:url => q_url).first
  end
  
  # Instance Methods
  def to_param
    "#{id}-#{name}".parameterize
  end
  
  def category_text
    Organization.category_text(category_id)
  end
  
  def update_cache!(condition_id)
    review_cache = cache_review_stats.with_condition(condition_id).first
    
    if review_cache.nil?
      review_cache = cache_review_stats.create(:condition_id => condition_id)
    end
    
    review_cache.num_reviews = reviews.with_condition(condition_id).count
    review_cache.avg_review = reviews.with_condition(condition_id).average(:rating) || 0
    
    review_cache.save!
  end
  
  private
  
  def clean_url
    unless url.blank?
      query_url = self.url
      unless query_url =~ /\Ahttps?:\/\//
        query_url = "http://" + query_url
      end
      
      components = URI.split(query_url)
      
      res = ""
      if components[2] =~ /yelp\.com/ and components[5] =~ /\A\/biz\//
        res << "http://www.yelp.com"
        res << components[5]
        self.url_type = "yelp"
      end
      self.url = res
    end
  end
end

app/controllers/api/v1/organizations_controller.rb
class Api::V1::OrganizationsController < Api::V1::ApplicationController
  after_filter :track_google_analytics

  def index
    @organizations = Organization.paginate(:page => params[:page])

    unless params[:category].blank? or params[:category].downcase == "all"
      @organizations = @organizations.where(:category_id => params[:category])
    end

    @organizations = @organizations.joins(%(LEFT JOIN "cache_review_stats" ON "cache_review_stats"."organization_id" = "organizations"."id")).
                        select(%("organizations".*, "cache_review_stats"."num_reviews", "cache_review_stats"."avg_review")).
                        where(%("cache_review_stats"."condition_id" = 0 OR "cache_review_stats"."condition_id" IS NULL)).
                        order(%("cache_review_stats"."avg_review" DESC NULLS LAST)).
                        order(%("cache_review_stats"."num_reviews" DESC))
    
    if params[:latitude].present? and params[:longitude].present? and params[:radius].present?
      @organizations = @organizations.near([params[:latitude], params[:longitude]], params[:radius])
    elsif params[:latitude].present? or params[:longitude].present? or params[:radius].present?
      render :status => 500, :text => "Invalid API Call - must provide latitude, longitude, and radius"
    end
  end
  
  def show
    @organization = Organization.find(params[:id])
    @reviews = @organization.reviews.with_condition(0).paginate(:page => params[:page]).includes(:user)
  end
  
  private
  
  def track_google_analytics
    unless Rails.env.test?
      gabba = Gabba::Gabba.new(APP_CONFIG["google_analytics"][Rails.env], "revtilt.com")
      gabba.page_view("api call", request.fullpath)
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /organizations
  # GET /organizations.json
  def index
    authorize! :index, Organization
    
    @organizations = Organization.paginate(:page => params[:page])
    @organizations = @organizations.where(:category_id => params[:category]) unless params[:category].blank?
    @organizations = @organizations.joins(%(LEFT JOIN "cache_review_stats" ON "cache_review_stats"."organization_id" = "organizations"."id")).
                        where(%("cache_review_stats"."condition_id" = 0 OR "cache_review_stats"."condition_id" IS NULL)).
                        select(%("organizations".*, "cache_review_stats"."num_reviews", "cache_review_stats"."avg_review")).
                        order(%("cache_review_stats"."avg_review" DESC NULLS LAST)).
                        order(%("cache_review_stats"."num_reviews" DESC))
    @organizations = @organizations.near(params[:zipcode], 25) unless params[:zipcode].blank?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])
    
    authorize! :show, @organization
    
    @reviews = @organization.reviews.reverse_chronological.paginate(:page => params[:page])

    @review = Review.new
    @review.organization = @organization
    @review.condition_id = 0
    
    @title = @organization.name
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new
    @organization.name = params[:name]
    @organization.url = params[:url]
    @organization.homepage_url = params[:homepage_url]
    @organization.address = params[:address]

    authorize! :new, @organization

    @title = new_action_title

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])

    authorize! :edit, @organization
    
    @title = edit_action_title
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(permitted_params)

    authorize! :create, @organization

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html {
          existing_organization = Organization.with_url(@organization.url)
          if existing_organization.nil?
            @title = new_action_title; render action: "new"
          else
            redirect_to existing_organization, :notice => "Organization has already been submitted."
          end
        }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    authorize! :update, @organization

    respond_to do |format|
      if @organization.update_attributes(permitted_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { @title = edit_action_title; render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])

    authorize! :destroy, @organization

    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
  
  protected
  
  def permitted_params
    params.require(:organization).permit(:address, :category_id, :homepage_url, :latitude, :longitude, :name, :url)
  end
  
  def new_action_title
    "Share an Organization"
  end
  
  def edit_action_title
    "Edit Organization"
  end
end

app/helpers/api/v1/organizations_helper.rb
module Api::V1::OrganizationsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for @organization, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render "shared/error_messages", :object => f.object %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-xs-2' %>
    <div class="col-xs-6">
      <%= f.text_field :name, :class => 'form-control text_field' %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-xs-6 col-xs-offset-2">
      <span class="text-muted">
        Check out our <%= link_to "bookmarklet", bookmarklet_path, :target => "_blank" %> if you don't want to copy and paste!
      </span>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :category_id, :class => 'control-label col-xs-2' %>
    <div class="col-xs-6">
      <%= f.select :category_id, Organization.category_options.map { |k,v| [k, v] }, {}, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, :class => 'control-label col-xs-2' %>
    <div class="col-xs-6">
      <%= f.text_field :url, :class => 'form-control text_field', :placeholder => "e.g. 'www.yelp.com/biz/...'" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :homepage_url, :class => 'control-label col-xs-2' %>
    <div class="col-xs-6">
      <%= f.text_field :homepage_url, :class => 'form-control text_field', :placeholder => "optional" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-xs-2' %>
    <div class="col-xs-6">
      <%= f.text_field :address, :class => 'form-control text_field', :placeholder => "e.g. 1600 Pennsylvania Ave NW, Washington DC, 20006" %>
    </div>
  </div>
  
  <% if can? :manage, :all %>
    <div class="form-group">
      <%= f.label :latitude, :class => 'control-label col-xs-2' %>
      <div class="col-xs-6">
        <%= f.text_field :latitude, :class => 'form-control text_field' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :longitude, :class => 'control-label col-xs-2' %>
      <div class="col-xs-6">
        <%= f.text_field :longitude, :class => 'form-control text_field' %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-xs-6 col-xs-offset-2">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  organizations_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/organizations/_table.html.erb
<% with_join_columns ||= false %>

<table class="table table-hover">
  <tbody>
    <% organizations.each do |organization| %>
      <tr>
        <td class="col-xs-7">
          <span class="label label-default"><%= organization.category_text %></span>&nbsp;
          <%= link_to organization.name, organization %> <span class="text-muted one-line"><%= organization.display_location %></span>
          <% if can? :edit, organization %>
            <span class="one-line text-muted">
              | <%= link_to "edit", edit_organization_path(organization), :class => "text-muted" %>
            </span>
          <% end %>
          <% if can? :destroy, organization %>
            <span class="one-line text-muted">
              | <%= link_to "destroy", organization_path(organization), :method => :delete, :data => { :confirm => "Are you sure?" }, 
                    :class => "text-muted" %>
            </span>
          <% end %>
        </td>
        <td>
          <% if with_join_columns %>
            <% num_reviews = organization.num_reviews || 0 %>
            <% avg_review =  organization.avg_review || 0 %>
          <% else %>
            <% num_reviews = organization.cache_review_stats.with_condition(0).first.num_reviews rescue 0 %>
            <% avg_review =  organization.cache_review_stats.with_condition(0).first.avg_review rescue 0 %>
          <% end %>
          
          <%= content_tag :div, :class => "stars inline", "data-score" => avg_review, "data-readonly" => true do end %>
          <span class="one-line"><%= pluralize num_reviews, "Review" %></span>
        </td>
        <% if signed_in? %>
          <td>
            <%= render "relationships/organization_users/favorite_form", :organization => organization %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate organizations, :class => "center" %>

app/views/organizations/edit.html.erb
<h1>
  Edit Organization
</h1>
<br />
<%= render :partial => 'form' %>

app/views/organizations/index.html.erb
<div class="add-small-top pull-right">
  <%= link_to "Share an Organization",
              new_organization_path,
              :class => 'btn btn-primary' %>
</div>
 
<h1>Organizations</h1>
<br />

<% if @organizations.blank? %>
  <div class="alert alert-box alert-danger">
    <span class="label label-danger">Uh oh!</span>
    There are no organizations that meet these criteria yet! Be the first to contribute. Click <%= link_to "here", new_organization_path %>.
  </div>
<% else %>
  <%= render "table", :organizations => @organizations, :with_join_columns => true %>
<% end %>

app/views/organizations/new.html.erb
<h1>
  Share an Organization
</h1>
<br />
<%= render :partial => 'form' %>

app/views/organizations/show.html.erb
<%- model_class = Organization -%>
<% num_reviews = @organization.cache_review_stats.with_condition(0).first.num_reviews rescue 0 %>
<% avg_review =  @organization.cache_review_stats.with_condition(0).first.avg_review rescue 0 %>


<%= content_for :above_iframe do %>
  <div class="add-small-top pull-right">
    <%= render "relationships/organization_users/favorite_form", :organization => @organization %>
  </div>
  <div class="pull-right add-medium-top">
    <%= content_tag :div, :class => "stars inline", "data-score" => avg_review, "data-readonly" => true do end %>
    &nbsp;
    ( <%= pluralize num_reviews, "Review" %> )
    &nbsp;
  </div>

  <h1>
    <%= @organization.name %>
    <small><span class="one-line">( <%= @organization.category_text %> )</span></small>
  </h1>

  <%= @organization.display_location %>
  | <%= link_to "See Full Review", @organization.url, :target => "_blank" %>
  <% unless @organization.homepage_url.blank? %>
    | <%= link_to "See Homepage", @organization.homepage_url, :target => "_blank" %>
  <% end %>
  
  <% if can? :edit, @organization %>
    | <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_organization_path(@organization) %>
  <% end %>
  <% if can? :destroy, @organization %>
    | <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                organization_path(@organization),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
  <% end %>
<% end %>

<%= content_for :unbounded do %>
  <div class="center review_iframe">
    <%= content_tag :iframe, :id => "review_content", :src => @organization.url, :width => "1024px", :height => "300px" do end %>
  </div>
<% end %>

<h3>Reviews (<%= @reviews.count %>)</h3>

<%= render @reviews %>

<%= will_paginate @reviews, :class => "pagination pagination-centered" %>

<div class="review_form">
  <% if signed_in? %>
    <%= render "reviews/inline_form", :redirect => organization_path(@organization) %>
  <% else %>
    <%= link_to "Sign in to leave a review", new_review_path(:o_id => @organization.to_param), :class => "btn btn-success" %>
  <% end %>
</div>