config/routes.rb
RevTilt::Application.routes.draw do
  root :to => "pages#about"
  
  devise_for :users
  
  get "/about" => "pages#about"
  get "/bookmarklet" => "pages#bookmarklet"
  get "/favorites" => "pages#favorites"
  get "/press" => "pages#press"
  
  resources :organizations
  resources :reviews
  
  namespace :relationships do
    resources :organization_users do
      collection do
        post :favorite
        delete :unfavorite
      end
    end
  end

  namespace :api do
    namespace :v1 do
      get "/documentation" => "pages#documentation"
      resources :organizations, :only => [:index, :show]
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  
  # GET /reviews
  # GET /reviews.json
  def index
    authorize! :index, Review
    
    @reviews = Review.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    authorize! :show, @review

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new(:organization_id => params[:o_id])
    @review.user = current_user
    
    authorize! :new, @review

    @title = new_action_title

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
    
    authorize! :edit, @review
    
    @title = edit_action_title
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(permitted_params)
    @review.user = current_user
    
    authorize! :create, @review
    
    respond_to do |format|
      if @review.save
        format.html { redirect_to @review.organization || root_path, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { @title = new_action_title; render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    authorize! :update, @review

    respond_to do |format|
      if @review.update_attributes(permitted_params)
        format.html { redirect_to @review.organization || @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { @title = edit_action_title; render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    
    authorize! :destroy, @review
    
    @review.destroy

    respond_to do |format|
      format.html { redirect_to @review.organization || root_path }
      format.json { head :no_content }
    end
  end
  
  protected
  
  def permitted_params
    params.require(:review).permit(:condition_id, :content, :organization_id, :rating)
  end
  
  def new_action_title
    "New Review"
  end
  
  def edit_action_title
    "Edit Review"
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for @review, :html => { :class => 'form-vertical' } do |f| %>
  <%= render "shared/error_messages", :object => f.object %>
  
  <div class="form-group">
    <%= f.label nil, "Organization Name" %>
    <%= text_field_tag nil, (@review.organization.name rescue "N/A"), :disabled => "disabled", :class => "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label nil, "Location" %>
    <%= text_field_tag nil, (@review.organization.display_location rescue nil), :disabled => "disabled", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content, "My Review" %>
    <%= f.text_area :content, :class => 'text_area form-control', :rows => 5, :placeholder => "Write your review here" %>
  </div>
  <%= f.hidden_field :rating, :class => "rating" %>
  
  <% if current_user.admin? %>
    <div class="form-group">
      <%= f.label :condition_id %>
      <%= f.number_field :condition_id, :class => "form-control" %>
      <span class"helper-block">Only edit this if you're sure of what you're doing</span>
    </div>
    
    <div class="form-group">
      <%= f.label :organization_id %>
      <%= f.number_field :organization_id, :class => "form-control" %>
      <span class"helper-block">Only edit this if you're sure of what you're doing</span>
    </div>
  <% else %>
    <%= f.hidden_field :condition_id %>
    <%= f.hidden_field :organization_id %>
  <% end %>
  
  <div class="form-group">
    <%= f.submit "Leave review", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                @review.organization || root_path, :class => 'btn btn-default' %>
    &nbsp;
    <%= f.label :rating, "Overall rating", :class => 'control-label' %>
    &nbsp;
    <%= content_tag :div, :class => "stars inline", "data-score" => @review.rating do end %>
  </div>
<% end %>

app/views/reviews/_inline_form.html.erb
<% redirect ||= nil %>

<%= form_for @review, :html => { :class => 'form-vertical' } do |f| %>
  <div class="form-group">
    <%= f.text_area :content, :class => 'text_area form-control', :rows => 5, :placeholder => "Write your review here" %>
  </div>
  <%= f.hidden_field :condition_id %>
  <%= f.hidden_field :organization_id %>
  <%= f.hidden_field :rating, :class => "rating" %>
  
  <% unless redirect.blank? %>
    <%= hidden_field_tag :redirect, redirect %>
  <% end %>
  
  <div class="form-group">
    <%= f.submit "Leave review", :class => 'btn btn-primary' %>
    &nbsp;
    <%= f.label :rating, "Overall rating", :class => 'control-label' %>
    &nbsp;
    <div class="stars inline"></div>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div class="review-item">
  <div class="pull-right">
    <%= content_tag :div, :class => "stars inline", "data-score" => review.rating, "data-readonly" => true do end %>
  </div>
  <span class="label label-primary">
    <%= review.user.username rescue "N/A" %>
  </span>
  &nbsp;
  <span class="text-muted">written: <%= review.created_at.strftime("%b %d, %Y") %></span>

  &nbsp;
  <% if can? :edit, review %>
    <%= link_to "edit", edit_review_path(review), :class => "text-muted" %>
  <% end %>
  &nbsp;
  <% if can? :destroy, review %>
    <%= link_to "delete", review_path(review), :class => "text-muted", :method => :delete, :data => { :confirm => "Are you sure?" } %>
  <% end %>
  
  <br /><br />
  <div class="well">
    <%= simple_format review.content, :class => "review_content" %>
  </div>
</div>

app/views/reviews/edit.html.erb
<h1>
  Edit Review
</h1>
<br />

<%= render :partial => 'form' %>

app/views/reviews/index.html.erb
<div class="add-small-top pull-right">
  <%= link_to "New Review",
              new_review_path,
              :class => 'btn btn-primary' %>
</div>

<%- model_class = Review -%>
<h1>
  Reviews
</h1>
<br />
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:condition_id) %></th>
      <th><%= model_class.human_attribute_name(:organization_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to review.id, review_path(review) %></td>
        <td><%= review.rating %></td>
        <td><%= review.content %></td>
        <td><%= review.user_id %></td>
        <td><%= review.condition_id %></td>
        <td><%= review.organization_id %></td>
        <td><%=l review.created_at %></td>
        <td>
          <% if can? :edit, review %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_review_path(review), :class => 'btn btn-default btn-xs' %>
          <% end %>
          <% if can? :destroy, review %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        review_path(review),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @reviews, :class => "center" %>

app/views/reviews/new.html.erb
<h1>
  New Review
</h1>
<br />

<%= render :partial => 'form' %>

app/views/reviews/show.html.erb
<%- model_class = Review -%>
<h1>
  Review
</h1>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:rating) %>:</strong></dt>
  <dd><%= @review.rating %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @review.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @review.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:condition_id) %>:</strong></dt>
  <dd><%= @review.condition_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:organization_id) %>:</strong></dt>
  <dd><%= @review.organization_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              reviews_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_review_path(@review), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              review_path(@review),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>