config/routes.rb
RevTilt::Application.routes.draw do
  root :to => "pages#about"
  
  devise_for :users
  
  get "/about" => "pages#about"
  get "/bookmarklet" => "pages#bookmarklet"
  get "/favorites" => "pages#favorites"
  get "/press" => "pages#press"
  
  resources :organizations
  resources :reviews
  
  namespace :relationships do
    resources :organization_users do
      collection do
        post :favorite
        delete :unfavorite
      end
    end
  end

  namespace :api do
    namespace :v1 do
      get "/documentation" => "pages#documentation"
      resources :organizations, :only => [:index, :show]
    end
  end

end

app/views/layouts/_footer.html.erb
<div class="container">
  <ul class="horizontal">
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Email", "mailto:revtilt@gmail.com?subject=[Website] Hello" %></li>
    <li><%= link_to "Press", press_path %></li>
    <li><%= link_to "Twitter", APP_CONFIG["twitter_url"], :target => "_blank" %></li>
    <li><%= link_to "Bookmarklet", bookmarklet_path %></li>
    <li><%= link_to "API", api_v1_documentation_path %></li>
    <li><%= link_to "Github Repository", APP_CONFIG["github_repo"], :target => "_blank" %></li>
    <% unless Rails.env.production? %>
      <li><span class="label label-success"><%= Rails.env %></span></li>
    <% end %>

    <li class="pull-right">
      <iframe src="http://ghbtns.com/github-btn.html?user=cyrusstoller&repo=revtilt&type=watch&count=true"
        allowtransparency="true" frameborder="0" scrolling="0" width="90px" height="20"></iframe>
    </li>
    <li class="pull-right">
      <iframe src="http://ghbtns.com/github-btn.html?user=cyrusstoller&amp;type=follow" allowtransparency="true" frameborder="0" scrolling="0" width="140px" height="20px"></iframe>
    </li>
  </ul>
</div>

<div class="container">
  <div class="footer">
    Hosted by <%= link_to "Digital Ocean", "https://www.digitalocean.com/?utm_source=revtilt.com" %> &star;
    Copyright © 2015
  </div>
</div>

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= APP_CONFIG["google_analytics"][Rails.env] %>']);
  _gaq.push(['_setDomainName', 'revtilt.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/_header.html.erb
<div class="masthead">
  <div class="pull-right auth_links">
    <% if user_signed_in? %>
      <span class="text-muted">
        Hi <%= link_to (current_user.username || current_user.email), edit_user_registration_path, :class => "text-muted" %>! 
        <% if current_user.admin? %>
          <span class="label label-default">admin</span>
        <% end %>
        &nbsp; | &nbsp;
      </span>
    <% end %>
    <%= link_to "Share an Organization", new_organization_path, :class => 'text-muted' %><span class="text-muted"> &nbsp; | &nbsp;</span>
    <span class="label label-primary">Autism</span>
    <span class="text-muted">&nbsp; | &nbsp;</span>
    <% if user_signed_in? %>
      <%= link_to "Favorites", favorites_path, :class => "text-muted" %>
      <span class="text-muted">&nbsp; | &nbsp;</span>
      <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "text-muted" %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => "text-muted" %>
      <span class="text-muted">&nbsp; | &nbsp;</span>
      <%= link_to "Sign In", new_user_session_path, :class => "text-muted" %>
    <% end %>
  </div>
  
  <div class="slogan auth_links">
    Find Autism Friendly Places
  </div>
</div>

app/views/layouts/_search_bar.html.erb
<div class="header_bar">
  <div class="row">
    <div class="col-xs-7">
      <%= link_to root_path do %>
        <%= image_tag "logo.png", :id => "header_logo" %>
      <% end %>
      
      <div class="welcome-question inline">
        What are you looking for?
      </div>
    </div>
    
    <div class="col-xs-5">
      <%= form_tag organizations_path, :method => :get, :class => "form-horizontal search-bar" do %>
        <div class="form-group">
          <div class="col-xs-6 small-padding">
            <%= select_tag "category", options_for_select({ "all types" => nil }.merge(Organization.category_options), 
                            params[:category]), :class => "form-control" %>
          </div>
          <div class="col-xs-3 small-padding">
            <%= text_field_tag "zipcode", params[:zipcode], :placeholder => "Zipcode", :class => "form-control" %>
          </div>
          <div class="col-xs-2 small-padding">
            <%= submit_tag "Search", :class => "btn btn-default", :id => "search-btn" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag asset_path("favicon.png"), :type => 'image/png' %>
  <%= render :partial => 'layouts/google_analytics' %>
</head>
<body>

  <div class="container">
    <%= render "layouts/header" %>
  </div>
  <div class="container">
    <%= render "layouts/search_bar" %>
    <%= render "shared/flash_messages", :flash => flash %>
    <%= yield :above_iframe %>
  </div>
  
  <%= yield :unbounded %>
  
  <div class="container">
    <%= yield %>
  </div>
  
  <hr />
  
  <%= render "layouts/footer" %>
</body>

</html>